# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(default='none', max_length=200)),
                ('text', models.TextField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=500)),
                ('characters', models.CharField(max_length=500)),
                ('pinyin', models.CharField(max_length=500)),
                ('audio', models.CharField(default='none', max_length=500)),
                ('type', models.CharField(choices=[('phrase', 'phrase'), ('question', 'question')], max_length=6)),
                ('picture', models.CharField(default='none', max_length=500)),
                ('POS', models.CharField(default='none', max_length=100)),
                ('semanticType', models.CharField(default='none', max_length=100)),
                ('response1', models.CharField(default='none', max_length=25)),
                ('response2', models.CharField(default='none', max_length=25)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyId', models.CharField(max_length=100)),
                ('promptText', models.TextField()),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('vars', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyId', models.CharField(max_length=100)),
                ('option1or2', models.CharField(max_length=1)),
                ('ifStatement', models.TextField()),
                ('responseText', models.TextField()),
                ('setVariable', models.TextField()),
                ('nextPrompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nextPrompt', to='main.Prompt')),
                ('previousPrompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previousPrompt', to='main.Prompt')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('experience', models.IntegerField()),
                ('level', models.IntegerField()),
                ('wordsExposedTo', models.TextField()),
                ('levelOnLessons', models.TextField()),
            ],
        ),
    ]
