# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='promptId',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
