# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_story_vars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='experience',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='levelOnLessons',
            new_name='progressOnLessons',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
    ]
