# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170128_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='level',
            new_name='points',
        ),
    ]
